### PR TITLE
Hclust function choice

### PR DESCRIPTION
**Pull request by BananaCancer**
Here is the PR after our discussion is #17. The feature added is quite simple and simply adds another parameter to HclustParam.
Please tell me what you think!

### CODE REVIEW

**Comment by BananaCancer** [comment]
We also discussed in https://github.com/microbiome/bluster/pull/7 about the idea of changing the `cat` in the `show` function to something like `message`. 
Is this something we can change or do I let the print function be `cat`?

**Comment by LTLA** [comment]
My use of `cat` is based on BioC's use of `cat` in their `show` methods. I think this is reasonable as the entire purpose of the `show` generic is to display the contents of the object; if one were to suppress it, that would defeat the whole purpose of calling `show` in the first place. By comparison, other functions that do real stuff are printing messages as a side effect, in which case using `message` makes more sense if you want to get the function's result without the noise.

To illustrate: if I ran `suppressMessages(print(1:50))`, I would expect to see the vector contents printed out. That expectation would be the same if we replaced `1:50` with an arbitrary S4 class.

**Comment by LTLA** [comment]
Anyway, LGTM, I'll merge if there are no further edits pending.

**Comment by LTLA** [comment]
There's a missing trailing parenthesis in your `dontshow`.

also you might as well just add `fastcluster` to the `Suggests` and run the aformentioned example.

**Comment by BananaCancer** [comment]
My bad, it should be good now.

**Comment by LTLA** [comment]
Thanks, pushed to BioC-devel.

**Pull request merged**
